<div id="header">
    <h1 id="logo">
        <a href="/">
            <?php echo !empty($this->theme['logo']) ? '<img src="' . $this->theme['logo'] . '" alt="' . (!empty($this->theme['company']) ? Clean::xss($this->theme['company']) : '') . '" />' : ''; ?>
            <?php echo !empty($this->theme['company']) ? '<span>' . Clean::xss($this->theme['company']) . '</span>' : '<span>JobCastle</span>'; ?>
        </a>
    </h1>
</div>
<div id="searchblock" class="clearfix">
    <div class="wrapper">
        <form method="post" action="/search/" class="searchbar">
            <input type="text" name="search" id="q" placeholder="Enter a job title" maxlength="32" />
            <button type="submit" id="submit" value="search">search</button>
            <?php if (!empty($this->searchterm)): ?>
            <span class="searchterm">Search results for '<?php echo Clean::xss(substr($this->searchterm, 0, 32)); ?>'</span>
            <?php endif; ?>
            <select name="location" id="location" class="chzn" title="Location" style="visibility:hidden">
                <?php echo $this->dropdownLocations; ?>
            </select>
            <select name="category" id="category" class="chzn" title="Category" style="visibility:hidden">
                <?php echo $this->dropdownCategories; ?>
            </select>
            <?php if (empty($this->searchterm)): ?>
            <span class="filter">filter results by:</span>
            <?php endif; ?>
        </form>
    </div>
</div>
<div class="wrapper content">
    <?php if (isset($this->results)): ?>
    <div class="leftcolumn">
        <h2>Showing All Jobs</h2>
        <?php if (!empty($this->results)): ?>
        <ul id="searchresults">
            <?php
            $alt = false;
            foreach ($this->results as $result):

                $date_posted = $result['date_posted'];
                $location = $result['location'];
                $category = $result['category'];
                $schedule = $result['schedule'];
            ?>
                <li<?php echo $alt ? ' class="alt"' : ''; ?>>
                    <span class="date"><?php echo !empty($date_posted) ? date('F j Y', $date_posted) : ''; ?></span>
                    <h3 class="job-title"><?php echo Clean::xss($result['name']); ?></h3>
                    <?php
                    $url = '/job/details/';
                    if (!empty($location)) $url .= Clean::uristub($location) . '/';
                    if (!empty($category)) $url .= Clean::uristub($category) . '/';
                    $url .= Clean::uristub($result['uristub']) . '/';
                    ?>
                    <a href="<?php echo $url; ?>" class="right">View Details</a>
                    <?php if (!empty($schedule)): ?>
                    <span class="schedule"><?php echo Clean::xss($schedule); ?></span>
                    <?php endif; ?>

                    <?php if (!empty($location)): ?>
                    <span class="location"><?php echo Clean::xss($location); ?></span>
                    <?php endif; ?>
                </li>
                <?php $alt = !$alt; ?>
            <?php endforeach; ?>
        </ul>
        <?php else: ?>
        <h3>No search results were found</h3>
        <p>No search results were found matching your criteria. Please consider
        loosening your search criteria and try again.</p>
        <?php endif; ?>
    </div>
    <div class="rightcolumn">
        <?php if (!empty($this->jobsInCategory)): ?>
            <h4>Other Jobs In This Category</h4>
            <ul>
                <li><a href="/job/details/<?php echo Clean::xss($job['uristub']); ?>"><?php echo Clean::xss($job['name']); ?></a></li>
            </ul>
        <?php endif; ?>

        <?php if (!empty($this->jobsInLocation)): ?>
            <h4>Other Jobs At This Location</h4>
            <ul>
                <?php foreach ($this->jobsInLocation as $job): ?>
                <li><a href="/job/details/<?php echo Clean::xss($job['uristub']); ?>"><?php echo Clean::xss($job['name']); ?></a></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
    <?php else: ?>
    <div class="leftcolumn">
        <?php echo $this->partial('partials/global/flash-messenger.phtml');?>
    </div>
    <?php endif; ?>
</div>