<div class="block">
	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>

		<h2>Admin Dashboard</h2>
	</div>
	<!-- .block_head ends -->

	<div class="block_content">
        <?php
        $message = 'Welcome to the admin dashboard.';
        echo $this->partial(
            'partials/global/flash-messenger.phtml',
            array('message' => '<div class="message info"><p>' . $message . '</p></div>')
        );
        ?>
    </div>
</div>