<div class="container">
    <footer id="footer" class="clearfix">
        <div class="wrapper">
            <span class="right">
                Powered by JobCastle
            </span>
            &copy; <?php echo date('Y'); ?>
            <?php
            if (!empty($this->theme['website'])) {
                $text = '<a href="' . $this->theme['website'] . '" target="_blank">';
                $text .= !empty($this->theme['company']) ? $this->theme['company'] : 'JobCastle';
                $text .= '</a>';
            } else {
                $text = !empty($this->theme['company']) ? $this->theme['company'] : 'JobCastle';
            }
            echo $text;
            ?>. All rights reserved.
        </div>
    </footer>
</div>

<?php
$this->inlineScript()->appendFile('//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js');
$this->inlineScript()->appendFile('//ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js');
$this->inlineScript()->appendFile('/js/chosen.jquery.min.js');
$this->inlineScript()->appendFile($this->baseUrl('/js/plugins.js'));
$this->inlineScript()->appendFile($this->baseUrl('/js/global.js'));

echo $this->inlineScript();
echo $this->placeholder('js');
echo $this->partial('partials/global/error-form.phtml', array('errors' => !empty($this->errors) ? $this->errors : NULL));
?>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-10592015-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<?php if(!$this->isJobPosting && !empty($this->theme['dynamic_phone_tracking'])) echo $this->theme['dynamic_phone_tracking']; ?>
</body>
</html>