<div id="header">
    <h1 id="logo"><a href="/"><?php echo !empty($this->theme['company']) ? Clean::xss($this->theme['company']) : 'JobCastle'; ?></a></h1>
</div>
<div id="searchblock" class="clearfix">
    <div class="wrapper">
        <form method="post" action="/search/" class="searchbar">
            <input type="text" name="search" id="q" placeholder="Enter a job title" maxlength="32" />
            <button type="submit" id="submit" value="search">search</button>
            <?php if (!empty($this->searchterm)): ?>
            <span class="searchterm">Search results for '<?php echo Clean::xss(substr($this->searchterm, 0, 32)); ?>'</span>
            <?php endif; ?>
            <select name="location" id="location" class="chzn" title="Location" style="visibility:hidden">
                <?php echo $this->dropdownLocations; ?>
            </select>
            <select name="category" id="category" class="chzn" title="Category" style="visibility:hidden">
                <?php echo $this->dropdownCategories; ?>
            </select>
            <?php if (empty($this->searchterm)): ?>
            <span class="filter">filter results by:</span>
            <?php endif; ?>
        </form>
    </div>
</div>