<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="http://www.facebook.com/2008/fbml">
	<head>
		<meta charset="utf-8" />
		<meta content="<?php echo $this->csrfToken(); ?>" name="csrf-token" />
		<meta name="description" content="<?php echo !empty($this->description) ? $this->escape(substr($this->description, 0, 155)) : ''; ?>" />
		<meta property="og:type" content="website" />
		<meta property="og:url" content="<?php echo !empty($this->og['url']) ? $this->escape($this->og['url']) : ''; ?>" />
		<meta property="og:image" content="<?php echo !empty($this->og['image']) ? $this->escape($this->og['image']) : ''; ?>" />
		<meta property="og:site_name" content="Ruckus" />
		<meta property="og:title" content="<?php echo !empty($this->og['title']) ? $this->escape($this->og['title']) : 'Bayard Advertising'; ?>" />
		<meta property="og:description" content="<?php echo !empty($this->description) ? $this->escape(substr($this->description, 0, 155)) : ''; ?>" />
		<meta property="fb:admins" content="<?php echo !empty($this->og['admin']) ? $this->escape($this->og['admin']) : ''; ?>" />
		<?php
		echo $this->headTitle((!empty($this->theme['company']) ? $this->theme['company'] : 'JobCastle'), 'APPEND')->setSeparator(' | ');

        $this->headLink()->prependStylesheet('/css/chosen.css');
		$this->headLink()->prependStylesheet('/css/theme.css');
		$this->headLink()->prependStylesheet('/css/global.css');

		echo $this->headLink();
		echo $this->placeholder('css');
		echo $this->headScript();
		?>
	</head>
	<body id="home">