<div class="block">
    <div class="block_head">
        <div class="bheadl"></div>
        <div class="bheadr"></div>
        <h2>API Settings</h2>

		<ul>
			<li><a href="/api/docs/" class="btn long" target="_blank">Online Docs</a></li>
            <li><a href="/api/jobcastle-api-v1.1.tar.gz" class="btn long">Download Docs</a></li>
		</ul>
    </div>
    <div class="block_content">
        <p class="breadcrumb">
            <a href="/admin/">Admin</a> &raquo;
            <a href="/admin/settings/">Settings</a> &raquo;
            <strong>API</strong>
        </p>

        <?php echo $this->partial('partials/global/flash-messenger.phtml'); ?>

        <form action="/admin/settings/api/<?php echo (int) $this->client_id; ?>/" method="post" name="updateTheme" id="updateTheme">
            <p>
                <label for="company">Domain*:</label>
                <input type="text" class="text small" name="domain" id="domain" value="<?php echo !empty($this->apikeys['domain']) ? Clean::xss($this->apikeys['domain']) : ''; ?>" />
                <span class="note">This is the only allowable domain for making API requests.</span>
            </p>

            <?php if (!empty($this->apikeys)): ?>
            <p>
                <label for="company">Public Key:</label>
                <input type="text" readonly="readonly" class="text small" name="public" id="public" value="<?php echo !empty($this->apikeys['public']) ? Clean::xss($this->apikeys['public']) : ''; ?>" />
                <span class="note">The public key to use for API requests. Copy this value.</span>
            </p>
            <p>
                <label for="company">Private Key:</label>
                <input type="text" readonly="readonly" class="text small" name="private" id="private" value="<?php echo !empty($this->apikeys['private']) ? Clean::xss($this->apikeys['private']) : ''; ?>" />
                <span class="note">The private key to use for API requests. Copy this value.</span>
            </p>
            <?php endif; ?>

            <p>
                <input type="hidden" name="created_by" id="created_by" value="<?php echo !empty($this->settings['created_by']) ? (int) $this->settings['created_by'] : ''; ?>" />

                <?php if (empty($this->apikeys)): ?>
                <input class="submit long" type="submit" name="btnGenerate" id="btnGenerate" value="Generate API Keys" />
                <?php else: ?>
                <input class="submit long" type="submit" name="btnChangeDomain" id="btnChangeDomain" value="Update Domain" />
                <input class="submit long" type="submit" name="btnRegenerate" id="btnRegenerate" value="Regenerate API Keys" />
                <?php endif; ?>

            </p>
        </form>
    </div>
</div>
