<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
	<meta content="<?php echo $this->csrfToken(); ?>" name="csrf-token" />
	<meta http-equiv="X-UA-Compatible" content="IE=7" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php
	$this->headTitle((!empty($this->theme['company']) ? $this->theme['company'] : 'JobCastle'), 'APPEND')->setSeparator(' | ');
	if (!empty($this->title)) {
		foreach ((array) $this->title as $title) {
			$this->headTitle()->append($title);
		}
	}
	echo $this->headTitle();

    $this->headLink()->appendStylesheet('/css/admin/black/style.css');
    $this->headLink()->appendStylesheet('/css/admin/black/jquery.wysiwyg.css');
    $this->headLink()->appendStylesheet('/css/admin/black/facebox.css');
    $this->headLink()->appendStylesheet('/css/admin/black/visualize.css');
    $this->headLink()->appendStylesheet('/css/admin/black/date_input.css');

    echo $this->headLink();
    echo $this->placeholder('css');
    echo $this->headScript();
    ?>
    <!--[if lt IE 8]><style type="text/css" media="all">@import url("/css/admin/black/ie.css");</style><![endif]-->
</head>
<body>
	<div id="hld">
		<div class="wrapper">
			<div id="loginBlock" class="block small center login">
				<div class="block_head">
					<div class="bheadl"></div>
					<div class="bheadr"></div>
					<h2>Login</h2>
					<ul>
						<li><a href="/">back to the public site</a></li>
					</ul>
				</div>
				<div class="block_content">
                    <?php
                    echo $this->partial(
                        'partials/global/flash-messenger.phtml',
                        array('message' => '<div class="message info"><p>Enter your credentials below to login.</p></div>')
                    );
                    ?>
					<form action="/user/login/" method="post">
						<p>
							<label for="email">Email Address:</label><br />
							<input type="text" class="text" name="email" id="email" value="" placeholder="Enter your email address" />
						</p>
						<p>
							<label for="passphrase">Password:</label> <br />
							<input type="password" class="text" name="passphrase" id="passphrase" value="" placeholder="Enter your password" />
						</p>
						<p>
							<input type="submit" class="submit" value="Login" /> &nbsp;
							<!--input type="checkbox" class="checkbox" checked="checked" id="rememberme" /> <label for="rememberme">Remember me</label-->
                            or <a href="#" id="btnForgot" class="formToggle button">click here if you forgot your password</a>
						</p>
					</form>
				</div>
				<div class="bendl"></div>
				<div class="bendr"></div>
			</div>
            <div id="forgotBlock" class="block small center login hidden">
				<div class="block_head">
					<div class="bheadl"></div>
					<div class="bheadr"></div>
					<h2>Forgotten Password</h2>
					<ul>
						<li><a href="/">back to the public site</a></li>
					</ul>
				</div>
				<div class="block_content">
                    <?php echo $this->partial('partials/global/flash-messenger.phtml'); ?>
					<form action="/user/forgot/" method="post" id="forgotForm">
						<p>
							<label for="forgot_email">Email Address:</label> <br />
							<input type="text" class="text" name="forgot_email" id="forgot_email" value="" placeholder="Enter your email address" />
						</p>
						<p>
							<input type="submit" class="submit long" value="Reset my Password" />
							or <a href="#" id="btnLogin" class="formToggle button">click here to login</a>
						</p>
					</form>
				</div>
				<div class="bendl"></div>
				<div class="bendr"></div>
            </div>
		</div>
	</div>

	<!--[if IE]><script type="text/javascript" src="/js/admin/excanvas.js"></script><![endif]-->
	<script type="text/javascript" src="/js/admin/jquery.js"></script>
    <script type="text/javascript" src="/js/global.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.img.preload.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.filestyle.mini.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.wysiwyg.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.date_input.pack.js"></script>
	<script type="text/javascript" src="/js/admin/facebox.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.visualize.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.visualize.tooltip.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.select_skin.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.tablesorter.min.js"></script>
	<script type="text/javascript" src="/js/admin/ajaxupload.js"></script>
	<script type="text/javascript" src="/js/admin/jquery.pngfix.js"></script>
	<script type="text/javascript" src="/js/admin/custom.js"></script>
    <?php echo $this->partial('partials/global/error-form.phtml', array('errors' => !empty($this->errors) ? $this->errors : NULL)); ?>
    <script type="text/javascript">
    $(function() {
        $('.formToggle').live('click', function() {
            var $this = $(this);
            var id = $this.attr('id');
            if (id == 'btnLogin') {
                $('#forgotBlock').toggleClass('hidden');
                $('#loginBlock').toggleClass('hidden');
            } else {
                $('#loginBlock').toggleClass('hidden');
                $('#forgotBlock').toggleClass('hidden');
            }
            return false;
        });
    })
    </script>
    <?php
    echo $this->inlineScript();
    echo $this->placeholder('js');
    ?>

</body>
</html>